repos:
  - repo: https://github.com/bridgecrewio/checkov.git
    rev: 3.2.497
    hooks:
      - id: checkov
        name: Checkov (IaC)
        args: ["-d", ".", "--compact", "--quiet"]
        pass_filenames: false
        verbose: true

  - repo: local
    hooks:
      - id: trivy
        name: Trivy (Filesystem)
        entry: trivy fs .
        language: system
        pass_filenames: false
