apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-latency
  namespace: chaos-mesh
spec:
  action: delay
  mode: all
  selector:
    namespaces:
      - node-k8s-app
    labelSelectors:
      app: node-k8s-app
  delay:
    latency: "100ms"
    correlation: "100"
    jitter: "0ms"
  duration: "30s"
  scheduler:
    cron: "@every 10m"
