resources:
  - ../../base

namespace: node-k8s-app

patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Rollout
      name: node-k8s-app
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
