resources:
  - ../../base

namespace: node-k8s-app

patchesJson6902:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Rollout
      name: node-k8s-app
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2 # Reduzido de 10 para 2 para caber no cluster econ√¥mico
