apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate-check
spec:
  args:
  - name: canary-hash
  metrics:
  - name: error-count
    interval: 20s
    count: 3
    initialDelay: 30s
    successCondition: result[0] == 0
    failureLimit: 0
    provider:
      prometheus:
        address: http://prometheus-server.monitoring.svc.cluster.local
        query: |
          sum(http_requests_total{status=~"5.*", rollouts_pod_template_hash="{{args.canary-hash}}"}) or on() vector(0)
