apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate-check
spec:
  metrics:
  - name: error-rate
    interval: 30s
    count: 3
    initialDelay: 1m
    successCondition: result[0] <= 0.01
    failureLimit: 0
    provider:
      prometheus:
        address: http://prometheus-server.monitoring.svc.cluster.local
        query: |
          max(
            rate(http_requests_total{status=~"5.*"}[2m])
            /
            rate(http_requests_total[2m])
          )
