apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate-check
spec:
  metrics:
  - name: error-rate
    interval: 30s
    count: 3
    initialDelay: 1m
    successCondition: result[0] <= 0.01
    failureLimit: 0
    provider:
      prometheus:
        address: http://prometheus-server.monitoring.svc.cluster.local
        query: |
          max(
            (sum by (rollouts_pod_template_hash) (rate(http_requests_total{status=~"5.*"}[1m])) or on() vector(0))
            /
            (sum by (rollouts_pod_template_hash) (rate(http_requests_total[1m])) or on() vector(1))
          )
