apiVersion: v1
kind: Service
metadata:
  name: node-k8s-service
  labels:
    app: node-k8s-app
  annotations:
    beta.cloud.google.com/backend-config: '{"default": "node-app-be-config"}'
spec:
  selector:
    app: node-k8s-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
