apiVersion: v1
kind: Service
metadata:
  name: node-k8s-service
  namespace: node-k8s-app
  labels:
    app: node-k8s-app
  annotations:
    beta.cloud.google.com/backend-config: '{"default": "node-app-be-config"}'
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: node-k8s-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
